const faces=['assets/face1.png','assets/face2.png','assets/face3.png','assets/face4.png','assets/face5.png','assets/litterio_coin_face.png'];
const symbols=[...faces,'🍒','🔔','🍀','7️⃣','BAR'];
let credits=Number(localStorage.funlotCredits||1500), lotcoins=Number(localStorage.funlotCoins||0), bonusKicks=0, bj={};
const $=q=>document.querySelector(q), $$=q=>document.querySelectorAll(q);
function save(){localStorage.funlotCredits=credits;localStorage.funlotCoins=lotcoins;$('#credits').textContent=credits;$('#lotcoins').textContent=lotcoins}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function rnd(a){return a[Math.floor(Math.random()*a.length)]}function bet(id){let v=Math.max(1,Number($(id).value||1)); if(credits<v){toast('Crediti insufficienti'); return 0} credits-=v; save(); return v}
function symHtml(s){return s.includes('assets/')?`<img src="${s}" alt="face">`:`<b>${s}</b>`}
$$('#gamesNav button').forEach(b=>b.onclick=()=>{$$('#gamesNav button').forEach(x=>x.classList.remove('active'));$$('.game').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.game).classList.add('active')});
$('#dailyBonus').onclick=()=>{let last=localStorage.funlotBonusDay, today=new Date().toDateString(); if(last===today)return toast('Bonus già preso oggi'); credits+=500; localStorage.funlotBonusDay=today; save(); toast('+500 crediti bonus FunLot')};
function initSlot(){const reels=$('#reels');reels.innerHTML='';for(let i=0;i<5;i++){let r=document.createElement('div');r.className='reel';r.innerHTML='<div class="symbol">7️⃣</div><div class="symbol">BAR</div><div class="symbol">🍒</div>';reels.appendChild(r)}}
function spin(){let b=bet('#slotBet'); if(!b)return; $('#slotMsg').textContent='Gira...'; const middle=[]; $$('.reel').forEach((r,i)=>{r.classList.remove('winLine'); let arr=[rnd(symbols),rnd(symbols),rnd(symbols)]; middle[i]=arr[1]; r.innerHTML=arr.map(x=>`<div class="symbol">${symHtml(x)}</div>`).join(''); r.animate([{transform:'translateY(-40px)'},{transform:'translateY(0)'}],{duration:300+i*90})}); setTimeout(()=>checkSlot(middle,b),850)}
function checkSlot(m,b){let allFaces=m.every(x=>faces.includes(x)); let allSame=m.every(x=>x===m[0]); let allLitterio=m.every(x=>x==='assets/litterio_coin_face.png'); if(allFaces){credits+=b*30; $$('.reel').forEach(r=>r.classList.add('winLine')); toast('Hai Vinto Coglione!!'); $('#slotMsg').textContent=`Riga di faccine! Vinci ${b*30} crediti.`} else if(allSame){credits+=b*12; $('#slotMsg').textContent=`Cinquina! Vinci ${b*12} crediti.`} else if(m.filter(x=>x==='7️⃣').length>=3){credits+=b*5; $('#slotMsg').textContent=`Tre o più 7: vinci ${b*5}.`} else $('#slotMsg').textContent='Niente, FunLot ringrazia.'; if(allLitterio){bonusKicks=7; $('#kickBtn').disabled=false; lotcoins++; toast('BONUS LITTERIO + 1 LOTCOIN!'); $('#bonusMsg').textContent='Bonus attivo: 7 calci disponibili.'} save()}
$('#spinBtn').onclick=spin; initSlot();
function pokerDeck(){let vals=['A','K','Q','J','10','9','8','7'];let deck=[];vals.forEach((v,i)=>faces.forEach((f,j)=>deck.push({v,img:f,rank:i}))); return deck.sort(()=>Math.random()-.5)}
$('#dealPoker').onclick=()=>{let b=bet('#pokerBet'); if(!b)return; let hand=pokerDeck().slice(0,5); $('#pokerCards').innerHTML=hand.map(c=>`<div class="card"><small>${c.v}</small><img src="${c.img}"><span>${c.v}</span></div>`).join(''); let counts={};hand.forEach(c=>counts[c.v]=(counts[c.v]||0)+1); let vals=Object.values(counts).sort((a,b)=>b-a); let mult=0,name='Carta alta, zero gloria'; if(vals[0]===4){mult=25;name='Poker!'} else if(vals[0]===3&&vals[1]===2){mult=12;name='Full!'} else if(vals[0]===3){mult=6;name='Tris!'} else if(vals[0]===2&&vals[1]===2){mult=3;name='Doppia coppia'} else if(vals[0]===2){mult=2;name='Coppia'} if(mult){credits+=b*mult; $('#pokerMsg').textContent=`${name} Vinci ${b*mult} crediti.`} else $('#pokerMsg').textContent=name; save()};
$('#spinRoulette').onclick=()=>{let b=bet('#roulBet'); if(!b)return; let pick=Math.max(0,Math.min(36,Number($('#roulNumber').value||0))); let n=Math.floor(Math.random()*37); let w=$('#wheel'); w.style.transform=`rotate(${720+Math.random()*720}deg)`; setTimeout(()=>{w.textContent=n; if(n===pick){credits+=b*7; let t=`Numero ${n}! Pagamento ridicolo 7 a 1: +${b*7}`; if(n===7){lotcoins++;t+=' e +1 LotCoin!'} $('#rouletteMsg').textContent=t; toast('Roulette Funcessen paga!')} else $('#rouletteMsg').textContent=`È uscito ${n}. Hai puntato ${pick}.`; save()},900)};
const suits=['♠','♥','♦','♣'];function deck21(){let vals=['A','2','3','4','5','6','7','8','9','10','J','Q','K'],d=[];vals.forEach(v=>suits.forEach(s=>d.push({v,s})));return d.sort(()=>Math.random()-.5)}function val(hand){let sum=0,aces=0;hand.forEach(c=>{if(c.v==='A'){aces++;sum+=11}else sum+=['K','Q','J'].includes(c.v)?10:Number(c.v)});while(sum>21&&aces){sum-=10;aces--}return sum}function drawCards(id,hand){$(id).innerHTML=hand.map(c=>`<div class="card"><small>${c.s}</small>${c.v}</div>`).join('')}function bjEnd(msg,win){if(win>0)credits+=win; $('#bjMsg').textContent=msg; save()}$('#newBj').onclick=()=>{let b=bet('#bjBet'); if(!b)return; bj={bet:b,deck:deck21(),p:[ ],d:[ ],over:false}; bj.p.push(bj.deck.pop(),bj.deck.pop()); bj.d.push(bj.deck.pop(),bj.deck.pop()); drawCards('#playerCards',bj.p);drawCards('#dealerCards',bj.d); $('#bjMsg').textContent=`Tua mano ${val(bj.p)}, banco ${val(bj.d)}.`};$('#hitBj').onclick=()=>{if(!bj.deck||bj.over)return; bj.p.push(bj.deck.pop()); drawCards('#playerCards',bj.p); let v=val(bj.p); if(v>21){bj.over=true; bjEnd('Sballato. Banco felice.',0)} else $('#bjMsg').textContent=`Tua mano ${v}.`};$('#standBj').onclick=()=>{if(!bj.deck||bj.over)return; while(val(bj.d)<17)bj.d.push(bj.deck.pop()); drawCards('#dealerCards',bj.d); let p=val(bj.p),d=val(bj.d); bj.over=true; if(d>21||p>d)bjEnd(`Hai vinto: ${p} contro ${d}.`,bj.bet*2); else if(p===d)bjEnd(`Pareggio ${p}. Ti torna la puntata.`,bj.bet); else bjEnd(`Perso: ${p} contro ${d}.`,0)};
const diceFace=['','⚀','⚁','⚂','⚃','⚄','⚅'];$('#rollDice').onclick=()=>{let b=bet('#diceBet'); if(!b)return;let a=1+Math.floor(Math.random()*6),c=1+Math.floor(Math.random()*6);$('#die1').textContent=diceFace[a];$('#die2').textContent=diceFace[c]; if(a===6&&c===6){credits+=b*10;$('#diceMsg').textContent=`Doppio 6! Vinci ${b*10}.`}else if(a===c){credits+=b*3;$('#diceMsg').textContent=`Doppio ${a}! Vinci ${b*3}.`}else $('#diceMsg').textContent=`${a+c}. Niente.`;save()};
function kick(){if(bonusKicks<=0)return; bonusKicks--; let win=20+Math.floor(Math.random()*81); credits+=win; let img=$('#litterioKick'); img.classList.add('kick'); setTimeout(()=>img.classList.remove('kick'),160); let m=document.createElement('div');m.className='money';m.textContent='€ '+win;m.style.left=(25+Math.random()*55)+'%';$('#moneyRain').appendChild(m); setTimeout(()=>m.remove(),1000); $('#bonusMsg').textContent=`Calcio riuscito: +${win}. Calci rimasti: ${bonusKicks}`; if(bonusKicks===0){$('#kickBtn').disabled=true; $('#bonusMsg').textContent+=' Bonus finito.'} save()}
$('#kickBtn').onclick=kick; $('#forceBonus').onclick=()=>{bonusKicks=7;$('#kickBtn').disabled=false;$('#bonusMsg').textContent='Demo bonus attiva: 7 calci.'};
save();
