const faces=['face_stephan.png','face_casco.png','face_beard.png','face_smile.png','face_blond.png','face_red.png','litterio.png'];
const names=['Stephan','Casco','Beard','Sorriso','Blond','Red','Litterio'];
let balance=Number(localStorage.funlotBalance||1500), bet=25, selected='slot';
const $=s=>document.querySelector(s); const asset=n=>`assets/faces/${n}`;
function save(){localStorage.funlotBalance=balance; $('#balance').textContent=balance}
function toast(t){const el=$('#toast'); el.textContent=t; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600)}
window.addEventListener('load',()=>{save(); setTimeout(()=>$('#loader').classList.add('hide'),1800)})
function showLobby(){ $('#game').classList.add('hidden'); $('#lobby').classList.remove('hidden') }
function openWallet(){toast(`Wallet FunLot: ${balance} LotCoin. Demo, soldi finti, gloria vera.`)}
function resetGame(){balance=1500; save(); toast('Saldo demo ripristinato a 1500 LC')}
function openGame(g){selected=g; $('#modalTitle').textContent='Puntata per '+({slot:'Faces of Funseven',poker:'Funseven Poker',roulette:'Funcessen Roulette',kick:'Litterio Kick Bonus'}[g]); $('#betModal').classList.remove('hidden')}
function setBet(v){bet=v; $('#customBet').value=v}
function startSelectedGame(){bet=Math.max(1,Number($('#customBet').value||bet)); if(balance<bet){toast('Saldo insufficiente, fai reset demo.');return} $('#betModal').classList.add('hidden'); $('#loader').classList.remove('hide'); $('#loadText').textContent='Caricamento gioco con grafica casinò online...'; setTimeout(()=>{ $('#loader').classList.add('hide'); renderGame(selected)},1200)}
function renderGame(g){$('#lobby').classList.add('hidden'); $('#game').classList.remove('hidden'); if(g==='slot') slot(); if(g==='poker') poker(); if(g==='roulette') roulette(); if(g==='kick') kick()}
function randFace(){return Math.floor(Math.random()*faces.length)}
function slot(){
 $('#game').innerHTML=`<div class="machine"><h1 class="machine-title">FACES OF FUNSEVEN SLOTS</h1><div class="stats"><div class="stat">BET <b id="betv">${bet}</b> LC</div><div class="stat">WIN <b id="winv">0</b> LC</div><div class="stat">Bonus: 5 Litterio</div></div><div class="reels" id="reels">${[0,1,2,3,4].map(i=>`<div class="reel"><img class="symbol" src="${asset(faces[i])}"></div>`).join('')}</div><div class="controls"><button class="primary" onclick="spinSlot()">SPIN</button><button onclick="openGame('slot')">Cambia puntata</button><button onclick="showLobby()">Esci</button></div><p style="text-align:center;color:#aaa">Riga piena di faccine uguali = messaggio storico. 5 Litterio = bonus calci.</p></div>`
}
function spinSlot(){ if(balance<bet){toast('Saldo insufficiente');return} balance-=bet; save(); $('#winv').textContent='0'; const reels=[...document.querySelectorAll('.reel')]; reels.forEach(r=>r.classList.add('spinning','winline')); let results=[]; reels.forEach((r,i)=>{setTimeout(()=>{let n=randFace(); if(Math.random()<0.06)n=6; results[i]=n; r.querySelector('img').src=asset(faces[n]); r.classList.remove('spinning'); if(i===4) settleSlot(results)},700+i*330)})}
function settleSlot(res){let win=0; if(res.every(x=>x===6)){toast('BONUS LITTERIO SBLOCCATO!'); setTimeout(()=>kick(true),700); win=bet*7}else if(res.every(x=>x===res[0])){win=bet*50; toast('Hai Vinto Coglione!! JACKPOT FACCINE!')}else{let counts={}; res.forEach(x=>counts[x]=(counts[x]||0)+1); let max=Math.max(...Object.values(counts)); if(max>=3){win=bet*max; toast(`${max} facce uguali: vincita FunLot!`)} else toast('Niente linea, Litterio si tiene i LotCoin.')} balance+=win; save(); $('#winv')&&($('#winv').textContent=win); document.querySelectorAll('.reel').forEach(r=>r.classList.toggle('winline',win>0))}
function poker(){balance-=bet; save(); let hand=[0,1,2,3,4].map(randFace); let counts={}; hand.forEach(x=>counts[x]=(counts[x]||0)+1); let vals=Object.values(counts).sort((a,b)=>b-a); let mult= vals[0]===5?60:vals[0]===4?25:vals[0]===3&&vals[1]===2?12:vals[0]===3?6:vals[0]===2&&vals[1]===2?4:vals[0]===2?2:0; let win=bet*mult; balance+=win; save(); $('#game').innerHTML=`<div class="poker-table"><h1>FUNSEVEN POKER</h1><p>Carte ufficiali con facce FunLot. Puntata ${bet} LC.</p><div class="hand">${hand.map(i=>`<div class="card"><img src="${asset(faces[i])}"><span>${names[i]}</span><b>7♠</b></div>`).join('')}</div><h2>${win?`Vinto ${win} LC`:'Mano da dimenticare'}</h2><div class="controls"><button class="primary" onclick="openGame('poker')">Nuova mano</button><button onclick="showLobby()">Lobby</button></div></div>`}
function roulette(){ $('#game').innerHTML=`<div class="roulette"><h1>FUNCESSEN ROULETTE</h1><p>Qui si paga 7 a 1, perché il 36 è da dilettanti.</p><div id="wheel" class="wheel">?</div><div class="controls"><button onclick="betNumber(7)">Punta sul 7</button><button onclick="betNumber('random')">Punta casuale</button><button onclick="showLobby()">Lobby</button></div><div id="rouletteResult"></div></div>`}
function betNumber(n){ if(balance<bet){toast('Saldo insufficiente');return} balance-=bet; save(); let chosen=n==='random'?Math.floor(Math.random()*8):7; let result=Math.floor(Math.random()*8); let w=$('#wheel'); w.style.transform=`rotate(${1080+result*45}deg)`; setTimeout(()=>{w.textContent=result; let win=result===chosen?bet*7:0; if(result===7){win+=7; toast('È uscito il 7: LotCoin Litterio pagato!')} if(win)toast(`Roulette: vinti ${win} LC`); else toast('Roulette crudele.'); balance+=win; save(); $('#rouletteResult').innerHTML=`<h2>Scelto ${chosen} — uscito ${result} — vincita ${win} LC</h2><img src="${asset('litterio.png')}" style="width:110px;border-radius:50%;border:4px solid #ffd45c">`},3000)}
function kick(fromBonus=false){ $('#game').classList.remove('hidden'); $('#lobby').classList.add('hidden'); $('#game').innerHTML=`<div class="kickbox"><h1>LITTERIO KICK BONUS</h1><p>${fromBonus?'Bonus da 5 Litterio nella slot.':'Minigioco demo.'} Ogni calcio genera un po’ di soldi.</p><div class="kick-area" id="kickarea"><img id="litterio" src="${asset('litterio.png')}"></div><div class="stats"><div class="stat">Calci <b id="kicks">0</b>/10</div><div class="stat">Vinto <b id="kickwin">0</b> LC</div></div><div class="controls"><button class="primary" onclick="kickLitterio()">TIRA UN CALCIO</button><button onclick="showLobby()">Lobby</button></div></div>`}
let kicks=0,kickwin=0; function kickLitterio(){ if(kicks>=10){toast('Bonus finito.');return} kicks++; let add=7+Math.floor(Math.random()*bet); kickwin+=add; balance+=add; save(); $('#kicks').textContent=kicks; $('#kickwin').textContent=kickwin; const img=$('#litterio'); img.classList.add('hit'); setTimeout(()=>img.classList.remove('hit'),120); const c=document.createElement('div'); c.className='coin'; c.textContent='+'+add+' LC'; c.style.left=(45+Math.random()*15)+'%'; c.style.top='55%'; $('#kickarea').appendChild(c); setTimeout(()=>c.remove(),1000); if(kicks===10)toast(`Bonus chiuso: ${kickwin} LotCoin sputati!`)}
